[[shards]]
name = "Saint-Petersburg"
index = 0
address = "localhost:8080"

[[shards]]
name = "Moscow"
index = 1
address = "localhost:8081"

[[shards]]
name = "Yerevan"
index = 2
address = "localhost:8082"

[[shards]]
name = "Kazan"
index = 3
address = "localhost:8083"