name: CI
on: [push, pull_request]
permissions:
  contents: read
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.0'
        otp-version: '26.0'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run format check
      run: mix format --check-formatted
    - name: Run compile
      run: mix compile --warnings-as-errors --all-warnings
    - name: Run credo check
      run: mix credo --strict
    - name: Run gradient check
      run: mix gradient
    - name: Run tests
      run: mix test

  coverage:
    name: Check test coverage
    runs-on: ubuntu-latest
    needs: build
    if: ${{ !endsWith(github.ref, 'master') && !endsWith(github.ref, 'lab3') }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@61e01a43a562a89bfc54c7f9a378ff67b03e4a21 # v1.16.0
      with:
        elixir-version: '1.15.0'
        otp-version: '26.0'
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Go to the current app
      run: cd apps/${BRANCH_NAME}
    - name: Run tests
      run: mix test --cover --export-coverage default
    - name: Run coverage check
      run: mix test.coverage
